### ISSUE TITLE
InitgPty, Spanish banks and organizations

### ISSUE THREAD

**Issue by rmontagud** [digitick/php-sepa-xml#44]
Hello, 

Several Spanish banks (pain.008.001.02) require to add additional data related to the organization ID and other data, but the ID seems mandatory so far, when the initiating party is an organization so the final result looks like this

``` xml
<InitgPty>
    <Nm>Initiating Party Name</Nm>
    <Id>
        <OrgId>
            <Othr>
                <Id>CCNNNNNXZZZZZZZZ</Id>
            </Othr>
        </OrgId>
    </Id>
</InitgPty>
```

Source: [Spanish Bank Association](http://www.aebanca.es/cs/groups/public/documents/folletos/folleto-201305190.pdf) (pdf) page 18, in Spanish only, sorry :-/

**Comment by alexmoleiro** [comment]
I have coded a proxy to deal with Banc Sabadel, a spanish bank https://twitter.com/MoleiroAlex/status/586291614924021760

**Comment by israelromosen** [comment]
I had to do the <a href="https://github.com/digitick/php-sepa-xml/issues/44#issuecomment-91477985">modification</a> that indicates @montagud, but it does not work for me
I needed to include the tag called InitgPty->Id->OrgId->Othr->Id . For to do this, I <a href="https://github.com/digitick/php-sepa-xml/pull/47/files">added function</a> visitGroupHeader in CustomerDirectDebitTransferDomBuilder  and modified construct function GroupHeader like this:

	function __construct($messageIdentification, $initiatingPartyName, $initiatingPartyId $test = false)
    {
        $this->messageIdentification = $messageIdentification;
		$this->initiatingPartyId = $initiatingPartyId;
        $this->initiatingPartyName = StringHelper::sanitizeString($initiatingPartyName);
        $this->creationDateTime = new \DateTime();
    }
	
Now, works fine.

Thank you a lot of much for all

**Comment by alexmoleiro** [comment]
Israel:
Yo've done the same patch I suggested in my tweet. You can chek it and grab the class I've coded especially for spanish banking

**Comment by rmontagud** [comment]
Did you try with the latest stable release? Also, remember this project is no longer active since it's been forked to it's own organization since none of the authors works at Digitick right now https://github.com/php-sepa-xml/php-sepa-xml

**Comment by BenjaminPaap** [comment]
More important is that none of Digiticks employees seem responsible and they seem to have no interest in maintaining this anymore.

**Comment by eusonlito** [comment]
@alexmoleiro, I think that a abstract factory from GroupHeader is a better solution than a specific bank related function.

Check my example https://github.com/eusonlito/php-sepa-xml#sample-usage-directdebit-with-factory-and-custom-header and code https://github.com/eusonlito/php-sepa-xml/blob/master/lib/Digitick/Sepa/TransferFile/Factory/TransferFileFacadeFactory.php
