### ISSUE TITLE
Add new maintainers

### ISSUE THREAD

**Issue by BenjaminPaap** [digitick/php-sepa-xml#53]
@ianare: I noticed you are not maintaining this package anymore. If you are not interested in maintaining this could you please add some new maintainers that some of the pull requests get merged? We're using this in production and need some slightly changes which were proposed as pull requests already (Pull Request #40). Using my own fork and not letting others benefit from my changes feels wrong.

I know that time is something that everyone of us might need more of so let's share maintenance work. I personally would suggest adding the top 2 committers beneath yourself to the project if they also like this idea or someone who is fine with proposing himself to maintain this.

Thanks for your time and effort in coding this.

/cc @monofone, @ch3ric

**Comment by Nguimjeu** [comment]
@monofone and the other guys: Much appreciated!
