### ISSUE TITLE
New release Tag ? 

### ISSUE THREAD

**Issue by faboo03** [digitick/php-sepa-xml#58]
Hi, 
Any chance that you could release a new tag with the last modification (March 2014) ? 
Could be great to update the package without using the tag dev-master in composer. 

Thanks.

**Comment by BenjaminPaap** [comment]
Please use the maintained fork https://github.com/php-sepa-xml/php-sepa-xml

**Comment by faboo03** [comment]
Thanks, 
I did not know about that official fork ! 
You maybe could add a disclaimer on the main readme, to avoid people like me :p

**Comment by BenjaminPaap** [comment]
I'm working on that but no one from digitick is answering my mails for a year now. Unfortunately no one from us has push access to this repository.
